name: check_build_push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push :
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Flutter Action
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: "stable"

      - name: Build Flutter Web
        run: |
          flutter pub get
          flutter build web -t lib/main_production.dart






    # - uses: actions/checkout@v2
    # - uses: technote-space/get-diff-action@v6
    #   with:
    #     files: |
    #       pubspec.yaml

    # - name: pubspec.yaml changed
    # # check the file that we specifies to have in different files between the latest file and the one being commited in git or not
    #   if: contains(env.MATCHED_FILES , 'pubspec.yaml')
    #   steps:
    #     container:
    #       image: imageflutterpubgetsf
    #     - run: docker build -f update-imageflutterpubget/Dockerfile -t imageflutterpubgetsf .

    # - uses: actions/checkout@v2
    # - run: |
    #     docker build \
    #     -t ghcr.io/jjchinnapat/imageflutterweb:latest --build-arg GIT_PAT=${{ secrets.GIT_PAT }} .
    #     echo ${{ secrets.GIT_PAT }} | docker login ghcr.io -u jjchinnapat --password-stdin
    #     docker push ghcr.io/jjchinnapat/imageflutterweb:latest
